apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://dl-creator-loki:3100
    isDefault: false
    editable: true
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceUid: jaeger
          matcherRegex: "traceID=(\\w+)"
          name: TraceID
          url: "$${__value.raw}"
