apiVersion: apps/v1
kind: Deployment
metadata:
  name: rasa-chatbot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rasa-chatbot
  template:
    metadata:
      labels:
        app: rasa-chatbot
    spec:
      containers:
      - name: rasa-server
        image: gcr.io/YOUR_PROJECT/rasa-chatbot:latest
        ports:
        - containerPort: 5005
        env:
        - name: RASA_TOKEN
          valueFrom:
            secretKeyRef:
              name: rasa-secrets
              key: token
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5005
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5005
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: rasa-chatbot-service
spec:
  selector:
    app: rasa-chatbot
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5005
  type: LoadBalancer

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rasa-chatbot-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "rasa-chatbot-ip"
spec:
  rules:
  - host: chatbot.yourdomain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rasa-chatbot-service
            port:
              number: 80




